### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by jonny190** [yo8192/octo2influx#3]
Hey, you'll be sick of seeing my name but got another one: 

octoimport-octo2influx-1  | 2024-04-05 09:15:53    INFO octo2influx.py:456: === Retrieving tariffs...
octoimport-octo2influx-1  | Traceback (most recent call last):
octoimport-octo2influx-1  |   File "/usr/src/app/./octo2influx.py", line 457, in <module>
octoimport-octo2influx-1  |     for tariff in cfg['tariffs']:
octoimport-octo2influx-1  |   File "/usr/src/app/./octo2influx.py", line 130, in __getitem__
octoimport-octo2influx-1  |     return self.get_validated(key)
octoimport-octo2influx-1  |   File "/usr/src/app/./octo2influx.py", line 119, in get_validated
octoimport-octo2influx-1  |     value = super().__getitem__(key).get(self.params[key].cfg_type)
octoimport-octo2influx-1  |   File "/usr/local/lib/python3.10/site-packages/confuse/core.py", line 293, in get
octoimport-octo2influx-1  |     return templates.as_template(template).value(self, template)
octoimport-octo2influx-1  |   File "/usr/local/lib/python3.10/site-packages/confuse/templates.py", line 168, in value
octoimport-octo2influx-1  |     out.append(self.subtemplate.value(item, self))
octoimport-octo2influx-1  |   File "/usr/local/lib/python3.10/site-packages/confuse/templates.py", line 146, in value
octoimport-octo2influx-1  |     out[key] = typ.value(view[key], self)
octoimport-octo2influx-1  |   File "/usr/local/lib/python3.10/site-packages/confuse/templates.py", line 53, in value
octoimport-octo2influx-1  |     return self.get_default_value(view.name)
octoimport-octo2influx-1  |   File "/usr/local/lib/python3.10/site-packages/confuse/templates.py", line 62, in get_default_value
octoimport-octo2influx-1  |     raise exceptions.NotFoundError(u"{} not found".format(key_name))
octoimport-octo2influx-1  | confuse.exceptions.NotFoundError: tariffs#2.direction not found

this has only started since adding my export to the config file

**Comment by jonny190** [comment]
Never mind, I Typo'd 😂
